import "./globals.css";
import { Outfit } from "next/font/google";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";


export const metadata = {
  title: "IntelliNote-PDF",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8880385119289443"
     crossorigin="anonymous"></script>
        </head>
        <body className={outfit.className}>
            {/* ✅ Mobile View: Show warning message */}
            <div className="flex h-screen w-screen items-center justify-center sm:hidden">
            <h1 className="text-xl font-semibold text-center text-gray-600">
              This website is not optimized for mobile devices. Please access it on a desktop view.
            </h1>
          </div>
          {/* ✅ Desktop View: Show the full layout */}
          <div className="hidden sm:block">
            <Provider>{children}</Provider>
            <Toaster />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
